---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---


```{r}
library(rayshader)
library(raster)
library(magrittr)
```


```{r}
localtif <- raster::raster("../data/N33E126.hgt")
udo_bbox <- extent(c(126.864, 126.986, 33.413, 33.535))
udo_raster <- crop(localtif, udo_bbox)

#And convert it to a matrix:
elmat = matrix(raster::extract(udo_raster,raster::extent(udo_raster),buffer=1000),
               nrow=ncol(udo_raster),ncol=nrow(udo_raster))
```

```{r}
elmat %>%
  sphere_shade(texture = "bw") %>%
  add_water(detect_water(elmat), color="imhof1") %>%
  add_shadow(ray_shade(elmat, multicore=TRUE)) %>%
  add_shadow(ambient_shade(elmat, multicore=TRUE)) %>%
  plot_3d(elmat, zscale=5, theta=135, water=TRUE, watercolor = "#2255AA", waterdepth = 0.1, solid=TRUE, shadow=TRUE)
```


```{r}
localtif <- raster::raster("../data/N37E126.hgt")
#resampled <- aggregate(localtif, 4) 
resampled <- localtif
elmat = matrix(raster::extract(resampled,raster::extent(resampled),buffer=1000),
               nrow=nrow(resampled),
               ncol=ncol(resampled))
elmat %>%
  sphere_shade(texture = "imhof1") %>%
  add_water(detect_water(elmat)) %>%
  add_shadow(ray_shade(elmat,lambert=FALSE, anglebreaks = seq(85, 85, 1))) %>%
  add_shadow(lamb_shade(elmat)) %>%
  add_shadow(ambient_shade(elmat)) %>%
  plot_3d(elmat, zscale=30, theta=225, windowsize = c(1000, 1000))
```

