---
title: "R Notebook"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: inline
---


```{r message=FALSE, warning=FALSE}
library(rayshader)
library(raster)
library(magrittr)
library(esri2sf)
```


서울 도심부. DEM데이터는 NASA의 SRTM 30m 그리드를 이용. 
http://dwtkns.com/srtm30m/

두 개의 raster를 합쳐야한다.
경복궁을 중심으로 0.08도 범위를 선택.


```{r}
tif1 <- raster("../data/N37E126.hgt")
tif2 <- raster("../data/N37E127.hgt")
merged <- merge(tif1, tif2,tolerance=0.01)

cx <- 126.9761
cy <- 37.5775
r <- 0.081
ext <- extent(cx-r, cx+r, cy-r, cy+r)
city <- crop(merged, ext) 
```

matrix로 변환하고 그림자를 준다.

```{r message=FALSE, warning=FALSE}
elmat = matrix(extract(city, extent(city)),
               nrow=nrow(city),
               ncol=ncol(city))

z <- 100
model <- elmat %>%
  sphere_shade(texture = "imhof2", sunangle = 200) %>%
  add_shadow(ambient_shade(elmat, zscale=z, anglebreaks = seq(65, 65, 1))) %>%
  add_shadow(ray_shade(elmat, zscale=z, lambert=FALSE, anglebreaks = seq(65, 65, 1))) 
  
```


## 지하철 노선도

지하철 노선도를 ngii 서버에서 sf포맷으로 가져오자.

```{r message=FALSE, warning=FALSE}
rail <- "http://sd.ngii.go.kr:6080/arcgis/rest/services/NGII_EMAP/MapServer/502" %>%
  esri2sf()
rail$value <- 1
```

rasterize하자.

```{r message=FALSE, warning=FALSE}
rail_raster <- raster(ncol=ncol(city), nrow=nrow(city))
rail_raster <- setExtent(rail_raster, extent(city))
rail_raster <- rasterize(rail, rail_raster, rail$value, background=0)
rail_mat <- matrix(extract(rail_raster, extent(rail_raster)),
               nrow=nrow(rail_raster),
               ncol=ncol(rail_raster))
rail_mat <- rail_mat[, ncol(rail_mat):1]
```

2D 출력 

```{r message=FALSE, warning=FALSE}
model %>%
  add_water(rail_mat, color=col2rgb('#AA3388')) %>%
  plot_map()
```


3D 출력

```{r message=FALSE, warning=FALSE}
model %>%  
  add_water(rail_mat, color=col2rgb('#AA3388')) %>%
  plot_3d(elmat, zscale=8, 
          soliddepth=-60, 
          windowsize = c(1200, 1200), 
          fov=60, 
          water=TRUE)
```


