---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---


```{r}
library(rayshader)
library(raster)
library(magrittr)
library(esri2sf)
```


```{r}
localtif <- raster::raster("../data/N37E126.hgt")
resampled <- aggregate(localtif, 4) 
#resampled <- localtif
elmat = matrix(raster::extract(resampled,raster::extent(resampled),buffer=10),
               nrow=nrow(resampled),
               ncol=ncol(resampled))
model <- elmat %>%
  sphere_shade(texture = "imhof1") %>%
  add_water(detect_water(elmat)) %>%
  #add_shadow(ray_shade(elmat,lambert=FALSE, anglebreaks = seq(85, 85, 1))) %>%
  #add_shadow(ambient_shade(elmat, anglebreaks = seq(85, 85, 1))) %>%
  add_shadow(lamb_shade(elmat)) 
  
```
```{r}
model %>% plot_map()
```

```{r}
model %>%
  plot_3d(elmat, zscale=30, theta=225, windowsize = c(1000, 1000), 
          soliddepth = 100)

```

## 지하철 노선도

지하철 노선도를 ngii 서버에서 sf포맷으로 가져오자.

```{r}
rail <- "http://sd.ngii.go.kr:6080/arcgis/rest/services/NGII_EMAP/MapServer/502" %>%
  esri2sf()
rail$value <- 1
```

rasterize하자.

```{r}
rail_raster <- raster(ncol=ncol(resampled), nrow=nrow(resampled))
rail_raster <- setExtent(rail_raster, extent(resampled))
rail_raster <- rasterize(rail, rail_raster, rail$value, background=0)
rail_mat <- matrix(extract(rail_raster, extent(rail_raster),buffer=10),
               nrow=nrow(rail_raster),
               ncol=ncol(rail_raster))
rail_mat <- rail_mat[, ncol(rail_mat):1]
```

```{r}
red <- create_texture("#FF0000", "#FF0000", "#FF0000", "#FF0000", "#FF0000", cornercolors = NULL)

elmat %>%
  sphere_shade(texture = "imhof2") %>%
  add_water(rail_mat, color=col2rgb('#AA3311')) %>%
  plot_3d(elmat, zscale=30,  
          soliddepth = -100)
```

